# Logo (Font Awesome Class)
fa_logo: fa-cube

# Header
menu:
  Home: /
  Archives: /archives
  # About: /about.html
  # Contact: /contact.html

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
# twitter_url: https://twitter.com/?lang=en
# facebook_url: https://www.facebook.com/
# instagram_url: https://www.instagram.com/
# dribble_url: https://dribbble.com/
github_url: https://github.com/abruzzihraig
# googleplus_url: https://plus.google.com/
# behance_url: https://www.behance.net/
# fivehundredpx_url: https://500px.com/
email_url: mailto:abruzzi.hraig@gmail.com
# rss_url: \#

# Footer About Text
footer_about: "All of themes are shit on Hexo except this funny one. I just borrow it to leverage my journal for now. And hope someday I have enough time to build another one to perferm content better."

# Footer Copyright Line
footer_copyright: "Thanks for the guy's design <a href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a>"

